name: Main

on:
  push:
    branches:
      - master
      - dev
    tags:
      - '*'

  pull_request:
    branches:
      - master
      - dev

jobs:
  test_runner:
    runs-on: [ self-hosted, pdp-dev-builder ]
    steps:
      - run: echo "hello runner!"
