name: Main

on:
  push:
    branches:
      - master
      - dev
    tags:
      - '*'

  pull_request:
    branches:
      - master
      - dev

jobs:
  test_runner:
    runs-on: [ "self-hosted", "pat-builder" ]
    steps:
      - run: echo "hello runner!"
